#!/bin/bash
echo "📊 NDR Stack Status"
echo "==================="
echo ""
echo "🐳 Docker:"
docker compose ps 2>/dev/null || echo "  Not running"
echo ""
echo "🔍 Agent:"
curl -s http://localhost:3001/agent/status 2>/dev/null | python3 -m json.tool || echo "  Not running"
echo ""
echo "🌐 API:"
curl -s http://localhost:3000/health 2>/dev/null | python3 -m json.tool || echo "  Not running"
echo ""
echo "🖥️  UI:"
curl -s http://localhost:4200 > /dev/null 2>&1 && echo "  Running at http://localhost:4200" || echo "  Not running"
